export const IPC_CHANNELS = {
  WINDOW_CREATE: 'window:create',
  WINDOW_CLOSE: 'window:close',
  WINDOW_FOCUS: 'window:focus',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSED: 'window:closed',
  FS_READ: 'fs:read',
  FS_WRITE: 'fs:write',
  FS_LIST: 'fs:list',
  FS_DELETE: 'fs:delete',
  FS_WATCH: 'fs:watch',
  FS_UNWATCH: 'fs:unwatch',
  FS_CHANGED: 'fs:changed',
  AGENT_START: 'agent:start',
  AGENT_STOP: 'agent:stop',
  AGENT_MESSAGE: 'agent:message',
  AGENT_ABORT: 'agent:abort',
  AGENT_EVENT: 'agent:event',
  AGENT_EXIT: 'agent:exit',
  AGENT_TASK_CREATE: 'agent:task:create',
  AGENT_TASK_GET: 'agent:task:get',
  AGENT_TASK_CONTROL: 'agent:task:control',
  AGENT_TASK_EVENT: 'agent:task:event',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
